version: '3.8'
services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlserver:3306/productservice
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
      - spring_data_redis_host=rediscache
      - spring_data_redis_port=6379
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
      - rediscache
    networks:
      - internal

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=productservice
    volumes:
      - mysql_data:/var/lib/productservice/mysql
      - mysql_config:/etc/productservice/mysql/conf.d
    networks:
      - internal

  rediscache:
    hostname: rediscache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - cache:/data
    networks:
      - internal

volumes:
  mysql_data:
  mysql_config:
  cache:

networks:
  internal:
    name: internal